checkpoint: modules/voice_conversion_rvc/checkpoints/out.pth
f0_method: harvest
filter_radius: 3
hop_length: 128
index: null
pitch_shift: 0
python_executable: python
script_path: modules/voice_conversion_rvc/run_rvc.py
speaker_id: 0
