script_path: "modules/voice_conversion_rvc/run_rvc.py"
checkpoint: "modules/voice_conversion_rvc/dummy_model.pth"
index: null
python_executable: "python"
f0_method: harvest
speaker_id: 0
hop_length: 128
filter_radius: 3
pitch_shift: 0
